# .GitHub/actions/cloudformation-package-upload/action.yml
name: 'CloudFormation Package and Upload'
description: 'Packages a CloudFormation template and uploads it to S3'
inputs:
  s3_key_prefix:
    description: 'S3 Key Prefix'
    required: true
  s3_bucket:
    description: 'S3 Bucket Name'
    required: true
  sam_template:
    description: 'SAM template file'
    required: true
  app_name:
    description: 'app name'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        pwd
        ls -lah
        aws cloudformation package --template-file ${{ inputs.sam_template }} --s3-bucket ${{ inputs.s3_bucket }} --s3-prefix ${{ inputs.s3_key_prefix }} --output-template-file cloudformation_template.yaml
        aws s3 cp cloudformation_template.yaml s3://${{ inputs.s3_bucket }}/${{ inputs.s3_key_prefix }}/cloudformation_template.yaml
      shell: bash

    - run: |
        for paramFile in cfn/${{ github.event.inputs.app_name }}-dynamic-*.json; do
          aws s3 cp $paramFile s3://${{ inputs.s3_bucket }}/${{ inputs.s3_key_prefix }}/$(basename $paramFile)
        done
      shell: bash
