# .GitHub/actions/cloudformation-package-upload/action.yml
name: 'CloudFormation Package and Upload'
description: 'Packages a CloudFormation template and uploads it to S3'
inputs:
  s3_key_prefix:
    description: 'S3 Key Prefix'
    required: true
  s3_bucket:
    description: 'S3 Bucket Name'
    required: true
  sam_template:
    description: 'SAM template file'
    required: true
  tag:
    description: 'Release plugin tag/commit, used as discriminator in S3 bucket'
    required: true
  app_name:
    description: 'app name'
    required: true
  cf_template:
    description: 'CF template filename'
    required: false
    default: 'cloudformation_template.yaml'
  parameters_type:
    description: 'Type of parameters'
    required: false
    default: 'dynamic-parameters'
runs:
  using: "composite"
  steps:

    - name: Bake the tag into the CloudFormation Universal Stack template
      shell: bash
      run: |
        for file in cfn/${{ inputs.app_name }}-${{ inputs.parameters_type }-*.json; do
        if [[ -f "$file" ]]; then  # Check if it's a file and not an empty glob
          echo "Baking release commit ImageTag '${{ inputs.tag }}' into $file"
          jq --arg commit_id ${{ inputs.tag }} 'map(if .ParameterKey == "ImageTag" then .ParameterValue = $commit_id else . end)' "$file" > cfn/temp.json && mv cfn/temp.json "$file"
        fi
        done

    - run: |
        pwd
        ls -lah
        aws cloudformation package --template-file ${{ inputs.sam_template }} --s3-bucket ${{ inputs.s3_bucket }} --s3-prefix ${{ inputs.s3_key_prefix }} --output-template-file ${{ inputs.cf_template }}
        aws s3 cp ${{ inputs.cf_template }} s3://${{ inputs.s3_bucket }}/${{ inputs.s3_key_prefix }}/${{ inputs.cf_template }}
      shell: bash

    - run: |
        for file in cfn/${{ inputs.app_name }}-${{ inputs.parameters_type }}-*.json; do
          if [[ -f "$file" ]]; then  # Check if it's a file and not an empty glob
            echo "Processing $file"
            aws s3 cp $file s3://${{ inputs.s3_bucket }}/${{ inputs.s3_key_prefix }}/$(basename $file)
          fi
        done
      shell: bash
