name: 'Python Lambda Packer'
description: 'Packs a Python Lambda function zip'
inputs:
  function_name:
    description: 'Name of the Python function file'
    required: true
    default: 'lambda_function.py'
  working_dir:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ inputs.working_dir }}
        pip3 install -r requirements.txt --target ./lambda
        cd ./lambda
        ls -lah
        zip -r9 ../function.zip .
        cd ../
        echo $(pwd)
        ls -lah
        zip -g function.zip ${{ inputs.function_name }}
      shell: bash
