name: 'Deploy CloudFormation Stack'
description: 'Deploys a CloudFormation stack'
inputs:
  storage_account:
    description: 'CFN Storage AWS account ID'
    required: true
  aws_account:
    description: 'AWS account ID for deployment'
    required: true
  repository_name:
    description: 'GitHub repository name'
    required: true
  rel_tag:
    description: 'Release tag'
    required: true
  env:
    description: 'Environment'
    required: true
  aws_region:
    description: 'AWS region for deployment'
    required: false
    default: 'eu-central-1'
  capabilities:
    description: 'Capabilities'
    required: false
    default: 'CAPABILITY_NAMED_IAM'
  app_name:
    description: 'Stack name'
    required: true
  cfn_template_basename:
    description: 'CF template filename'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials CFN (download cfns)
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ inputs.storage_account }}:role/Github_Actions_Role
        aws-region: ${{ inputs.aws_region }}

    - run: |
        aws s3 cp s3://cfn-uni-${{ inputs.aws_region }}/${{ inputs.repository_name }}/${{ inputs.rel_tag }}/${{ inputs.app_name }}/ . --recursive
      shell: bash

    - name: Configure AWS credentials CFN deploy
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account }}:role/Github_Actions_Role
        aws-region: ${{ inputs.aws_region }}

    - name: Deploy Cloudformation Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ inputs.app_name }}
        capabilities: ${{ inputs.capabilities }}
        template: ${{ inputs.cfn_template_basename }}
        no-fail-on-empty-changeset: "1"
        parameter-overrides: |
          file:///${{ github.workspace }}/${{ inputs.app_name }}-${{ inputs.env }}.json
        timeout-in-minutes: 20
