name: 'Boemm Service Build Action'
description: 'Builds the Service jar using Maven Release Plugin'
inputs:
  github-token:
    description: "rw gh token for release-plugin. be carefull with permissions"
    required: true
    default: none
  java-version:
    description: 'Override java version. ex: 11'
    required: false
    default: '11'
  maven-args:
    description: 'override maven args. ex: -Darguments="-Dmaven.javadoc.skip=true"'
    required: false
    default: none
  maven-profile: 
    description: 'set maven profile, if needed. ex: -Pgithub-actions'
    required: false
    default: "-Pgithub-actions"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
      with:
        token: ${{ inputs.github-token }}   

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: "${{ inputs.java-version }}"
        cache: 'maven'
        server-id: github

    # Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          
    # Configure Git
    - name: Set up Git
      run: |
        git config --global user.email "<>"
        git config --global user.name "Release Plugin"
        echo "Build started on $(date)"
      shell: bash
    # Configure Git
    - name: Release-Prepare
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "Building the Service jar"
        mvn -B -Darguments='-Dmaven.javadoc.skip=true' clean initialize release:prepare "${{ inputs.maven-args }}" "${{ inputs.maven-profile }}"
      shell: bash
