name: 'ECR TAG AND Publish'
description: 'Publish Docker images to ECR'
inputs:
  registry:
    description: 'ECR registry URL'
    required: true
  repository:
    description: 'Repository name'
    required: true
  release_tag:
    description: 'Release tag'
    required: true
  tags:
    description: 'Comma-separated list of tags'
    required: true
  github_ref_name:
    description: 'GitHub reference name'
    required: true

runs:
  using: "composite"
  steps:
    - name: ECR LOGIN
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: build docker
      id: image-build
      shell: bash
      run: |
        image="${{ inputs.registry_path }}"
        imageUri="${{ steps.login-ecr.outputs.registry }}/${ image }"
        IFS=',' read -ra TAGS <<< "${{ inputs.tags }}""
        for tag in "${TAGS[@]}"; do
          echo "Pushing to ${imageUri}:${tag:0:7}"
          docker tag ${image}:${{ inputs.release_tag }} ${imageUri}:${tag:0:7}
        done
        if [[ "${{ inputs.github_ref_name }}" == "master" ]]; then
          docker tag ${image}:${{ inputs.release_tag }} ${imageUri}:latest    
        fi
        docker push --all-tags ${imageUri}
