name: 'Boemm DTO Build Action'
description: 'Builds the DTO jar using Maven Release Plugin'
inputs:
  java-version:
    description: 'Override java version. ex: 11'
    required: false
    default: '11'
  maven-args:
    description: 'override maven args. ex: -Darguments="-Dmaven.javadoc.skip=true"'
    required: false
    default: none
  maven-profile: 'set maven profile, if needed. ex: -Pgithub-actions'
    required: false
    default: "-Pgithub-actions"

runs:
  using: "composite"
  steps:
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
      with:
        token: ${{ secrets.GITHUB_TOKEN }}   

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: "${{ inputs.java-version }}"
        cache: 'maven'
        server-id: github

    # Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2
          
    # Configure Git
    - name: Set up Git
      run: |
        git config --global user.email "release@boemm.eu"
        git config --global user.name "Release Plugin"
        echo "Build started on $(date)"
    # Configure Git
    - name: Build DTO
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Building the DTO jar"
        mvn clean install release:prepare release:perform release:clean "${{ inputs.maven-args }}" "${{ inputs.maven-profile }}"
